--Script Version: Master - 1.1.0.0

USE [master]
GO

--this script is used to create the transit-performance database. change the name of the database and appropriate settings

IF EXISTS(SELECT * FROM sys.databases WHERE name='DBname')
DROP DATABASE DBname
GO

CREATE DATABASE [DBname]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DBname', FILENAME = N'...\DBname.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )  --update file location
 LOG ON 
( NAME = N'DBname_log', FILENAME = N'...\DBname_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%) --update file location
GO

ALTER DATABASE [DBname] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DBname].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DBname] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DBname] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DBname] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DBname] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DBname] SET ARITHABORT OFF 
GO

ALTER DATABASE [DBname] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DBname] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DBname] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DBname] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DBname] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DBname] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DBname] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DBname] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DBname] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DBname] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DBname] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DBname] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DBname] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DBname] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DBname] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DBname] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DBname] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DBname] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DBname] SET  MULTI_USER 
GO

ALTER DATABASE [DBname] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DBname] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DBname] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DBname] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DBname] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DBname] SET  READ_WRITE 
GO


